name: Build & Deploy MkDocs Site

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs
          npm install postcss postcss-cli autoprefixer cssnano html-validator-cli html-minifier-terser

      - name: Build CSS
        run: npx postcss theme/assets/src/styles.css -o theme/assets/dist/styles.min.css

      - name: Build MkDocs site
        run: mkdocs build

      - name: Minify HTML
        run: |
          npx html-minifier-terser site/**/*.html --collapse-whitespace --remove-comments --minify-css true --minify-js true --output-dir site-min
          mv site-min/* site/

      - name: Validate HTML
        run: npx html-validator-cli --directory site --verbose || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: ./site
